// <auto-generated />
namespace MyWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedOrderTable3ManyToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedOrderTable3ManyToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "201804291807378_addedOrderTable3ManyToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
